<a href="https://colab.research.google.com/github/Lourdes-Churacutipa/Repositorio-de-lourdes/blob/main/Lab3_1_packages_pandas_Peru.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Paquetes y Pandas en Python
## Ciencia de Datos Ambientales – Aplicado al Perú

**Objetivos de aprendizaje:**
- Comprender los paquetes de Python y cómo importarlos
- Trabajar con DataFrames de pandas para datos tabulares
- Cargar, explorar y manipular conjuntos de datos ambientales peruanos
- Realizar filtrado, agrupamiento y agregación

---

## 1. Paquetes y Módulos de Python

### 1.1 ¿Qué son los paquetes?

Un **paquete** (o librería) es una colección de código pre-escrito que extiende las capacidades de Python. En lugar de escribir todo desde cero, podemos importar paquetes que otros han desarrollado.

Paquetes clave para la ciencia de datos ambientales:
- `numpy` – computación numérica con arreglos
- `pandas` – manipulación y análisis de datos
- `scipy` – computación científica y estadística
- `matplotlib` – visualización
- `scikit-learn` – aprendizaje automático
- `geopandas`, `rasterio` – datos geoespaciales (muy usados en el MINAM e IGP)

### 1.2 Importando paquetes

In [ ]:
# Importar un paquete completo
import math

print(math.pi)
print(math.sqrt(16))

3.141592653589793
4.0

In [ ]:
# Importar con alias (apodo) – práctica muy común
import numpy as np
import pandas as pd

# Usamos np en lugar de numpy
arr = np.array([1, 2, 3, 4, 5])
print(f"Media: {np.mean(arr)}")

Media: 3.0

In [ ]:
# Importar funciones específicas de un paquete
from scipy import stats

# Podemos usar stats directamente
print(stats.norm.pdf(0))  # PDF de distribución normal en x=0

0.3989422804014327

### 1.3 Instalando paquetes en Colab

La mayoría de paquetes comunes están pre-instalados en Colab. Si necesitas algo más, usa `!pip install`:

In [ ]:
# Example: Install a package (this one is already installed, just for demonstration)
# !pip install pandas

# Verificar versiones instaladas
import numpy as np
import pandas as pd

print(f"Versión de pandas: {pd.__version__}")
print(f"Versión de numpy:  {np.__version__}")

Versión de pandas: 2.2.3
Versión de numpy:  2.1.3

### 1.4 Importaciones estándar para ciencia de datos

Estas importaciones son tan comunes que las verás al inicio de casi todos los notebooks de ciencia de datos ambientales:

In [ ]:
# Importaciones estándar
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats

# Para obtener gráficos más atractivos en los cuadernos
%matplotlib inline

---
## 2. Introducción a los Arreglos NumPy

Antes de adentrarnos en pandas, veamos brevemente los arreglos de NumPy, la base del cómputo numérico en Python.

In [ ]:
# Crear arreglos desde listas
# Temperaturas máximas diarias en Iquitos (°C) – datos SENAMHI
temperaturas = np.array([30.5, 31.2, 29.8, 32.1, 31.5, 30.9, 33.0])
print(f"Temperaturas: {temperaturas}")
print(f"Tipo: {type(temperaturas)}")

Temperaturas: [30.5 31.2 29.8 32.1 31.5 30.9 33. ]
Tipo: <class 'numpy.ndarray'>

In [ ]:
# Operaciones vectorizadas – se aplican a todos los elementos a la vez
# Convertir temperaturas de Celsius a Fahrenheit
temps_fahrenheit = temperaturas * 9/5 + 32
print(f"Celsius:    {temperaturas}")
print(f"Fahrenheit: {temps_fahrenheit}")

Celsius:    [30.5 31.2 29.8 32.1 31.5 30.9 33. ]
Fahrenheit: [86.9  88.16 85.64 89.78 88.7  87.62 91.4 ]

In [ ]:
# Funciones estadísticas integradas
print(f"Media:    {np.mean(temperaturas):.2f} °C")
print(f"Desv. Est:{np.std(temperaturas):.2f} °C")
print(f"Mínimo:   {np.min(temperaturas)} °C")
print(f"Máximo:   {np.max(temperaturas)} °C")
print(f"Mediana:  {np.median(temperaturas)} °C")

Media:    31.29 °C
Desv. Est:0.97 °C
Mínimo:   29.8 °C
Máximo:   33.0 °C
Mediana:  31.2 °C

In [ ]:
# Indexación booleana – muy poderosa para control de calidad
dias_calurosos = temperaturas > 31
print(f"Máscara días calurosos: {dias_calurosos}")
print(f"Temperaturas > 31°C:    {temperaturas[dias_calurosos]}")
print(f"Número de días calurosos: {np.sum(dias_calurosos)}")

Máscara días calurosos: [False  True False  True  True False  True]
Temperaturas > 31°C:    [31.2 32.1 31.5 33. ]
Número de días calurosos: 4

In [ ]:
# Arreglos 2D (matrices) – ejemplo: precipitación mensual (mm) en 3 cuencas peruanas
# Filas = cuencas, Columnas = meses (Ene-Abr)
precipitacion = np.array([
    [312, 285, 241, 198],   # Cuenca Madre de Dios
    [ 92,  88, 103,  98],   # Cuenca Mantaro
    [ 12,   8,   5,   3],   # Cuenca costera (Lima)
])

print(f"Forma: {precipitacion.shape}")  # (filas, columnas)
print(f"Precipitación media por cuenca:  {np.mean(precipitacion, axis=1)}")
print(f"Precipitación media por mes:     {np.mean(precipitacion, axis=0)}")

Forma: (3, 4)
Precipitación media por cuenca:  [259.    95.25   7.  ]
Precipitación media por mes:     [138.66666667 127.         116.33333333  99.66666667]

### 🔬 Ejercicio rápido 1 – NumPy

El IGP registra los valores de NDVI en 8 píxeles de una imagen Sentinel-2 sobre Loreto:

```python
ndvi = np.array([0.72, 0.85, 0.61, 0.78, 0.90, 0.55, 0.83, 0.69])
```

1. Calcula la media, mínimo y máximo del NDVI
2. ¿Cuántos píxeles tienen NDVI > 0.75? (bosque denso)
3. Calcula la desviación estándar

In [ ]:
# Tu código aquí
ndvi = np.array([0.72, 0.85, 0.61, 0.78, 0.90, 0.55, 0.83, 0.69])

# media = ???
# minimo = ???
# maximo = ???
# pixeles_bosque = ???
# desv_est = ???

---
## 3. Introducción a Pandas

Pandas es la librería de referencia para trabajar con datos tabulares. Proporciona dos estructuras de datos principales:
- **Series**: un arreglo 1D etiquetado (como una columna)
- **DataFrame**: una tabla 2D etiquetada (como una hoja de cálculo)

### 3.1 Pandas Series

In [ ]:
# Crear una Series – DAP (cm) de árboles en Madre de Dios
import pandas as pd

dap_valores = pd.Series([52.7, 38.4, 61.2, 29.5, 44.8],
                         name='DAP_cm')
print(dap_valores)
print(f"\nDAP medio: {dap_valores.mean():.1f} cm")

0    52.7
1    38.4
2    61.2
3    29.5
4    44.8
Name: DAP_cm, dtype: float64

DAP medio: 45.3 cm

In [ ]:
# Series con índice personalizado – conteo de especies en ANPs
conteo_especies = pd.Series(
    [312, 895, 148, 503, 221],
    index=['Manu', 'Pacaya-Samiria', 'Titicaca', 'Huascarán', 'Paracas'],
    name='Num_Especies_Aves'
)
print(conteo_especies)
print(f"\nEspecies en el Manu: {conteo_especies['Manu']}")

Manu              312
Pacaya-Samiria    895
Titicaca          148
Huascarán         503
Paracas           221
Name: Num_Especies_Aves, dtype: int64

Especies en el Manu: 312

### 3.2 Creando DataFrames

In [ ]:
# Crear DataFrame desde un diccionario – inventario forestal en Madre de Dios
datos_arboles = {
    'arbol_id': [1, 2, 3, 4, 5],
    'especie':  ['Swietenia macrophylla', 'Cedrela odorata',
                 'Cedrelinga cateniformis', 'Virola surinamensis',
                 'Swietenia macrophylla'],
    'dap_cm':   [52.7, 38.4, 61.2, 29.5, 44.8],
    'altura_m': [34.5, 28.1, 40.3, 22.6, 31.8],
    'parcela':  ['MDD_023', 'MDD_023', 'MDD_024', 'MDD_024', 'MDD_025']
}
datos_arboles

{'arbol_id': [1, 2, 3, 4, 5],
 'especie': ['Swietenia macrophylla',
  'Cedrela odorata',
  'Cedrelinga cateniformis',
  'Virola surinamensis',
  'Swietenia macrophylla'],
 'dap_cm': [52.7, 38.4, 61.2, 29.5, 44.8],
 'altura_m': [34.5, 28.1, 40.3, 22.6, 31.8],
 'parcela': ['MDD_023', 'MDD_023', 'MDD_024', 'MDD_024', 'MDD_025']}

In [ ]:
df = pd.DataFrame(datos_arboles)
df

   arbol_id                  especie  dap_cm  altura_m  parcela
0         1    Swietenia macrophylla    52.7      34.5  MDD_023
1         2          Cedrela odorata    38.4      28.1  MDD_023
2         3  Cedrelinga cateniformis    61.2      40.3  MDD_024
3         4      Virola surinamensis    29.5      22.6  MDD_024
4         5    Swietenia macrophylla    44.8      31.8  MDD_025

In [ ]:
# Información básica del DataFrame
print(f"Forma: {df.shape}")
print(f"Columnas: {df.columns.tolist()}")
print(f"\nTipos de datos:\n{df.dtypes}")

Forma: (5, 5)
Columnas: ['arbol_id', 'especie', 'dap_cm', 'altura_m', 'parcela']

Tipos de datos:
arbol_id      int64
especie      object
dap_cm      float64
altura_m    float64
parcela      object
dtype: object

### 3.3 Cargando datos desde archivos

In [ ]:
# Crear un archivo CSV de ejemplo – datos climáticos de estaciones SENAMHI
datos_ejemplo = """estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
IQUI_001,2024-07-01,30.5,18.2,88,Loreto
IQUI_001,2024-07-02,31.2,0.0,82,Loreto
IQUI_001,2024-07-03,29.8,32.5,91,Loreto
IQUI_001,2024-07-04,32.1,5.1,85,Loreto
IQUI_001,2024-07-05,31.5,0.0,80,Loreto
CUSC_002,2024-07-01,15.3,0.0,42,Cusco
CUSC_002,2024-07-02,14.8,2.3,55,Cusco
CUSC_002,2024-07-03,13.5,8.7,68,Cusco
CUSC_002,2024-07-04,16.2,0.0,45,Cusco
CUSC_002,2024-07-05,14.9,0.5,51,Cusco"""

with open('datos_senamhi.csv', 'w') as f:
    f.write(datos_ejemplo)

print("¡Archivo de datos creado!")

¡Archivo de datos creado!

In [ ]:
# Cargar CSV en DataFrame
clima_df = pd.read_csv('datos_senamhi.csv')
clima_df

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto
5,CUSC_002,2024-07-01,15.3,0.0,42,Cusco
6,CUSC_002,2024-07-02,14.8,2.3,55,Cusco
7,CUSC_002,2024-07-03,13.5,8.7,68,Cusco
8,CUSC_002,2024-07-04,16.2,0.0,45,Cusco
9,CUSC_002,2024-07-05,14.9,0.5,51,Cusco

In [ ]:
# Cargar datos desde URL – dataset público de CO2 de Mauna Loa
url = "https://raw.githubusercontent.com/datasets/co2-ppm/main/data/co2-mm-mlo.csv"
co2_df = pd.read_csv(url)
print(f"Se cargaron {len(co2_df)} filas de datos de CO2 de Mauna Loa")
co2_df.head()

Se cargaron 820 filas de datos de CO2 de Mauna Loa

              Date  Decimal Date  Average  Interpolated  Trend  Number of Days
1958-03  1958.2027        315.71   314.44            -1  -9.99           -0.99
1958-04  1958.2877        317.45   315.16            -1  -9.99           -0.99
1958-05  1958.3699        317.51   314.69            -1  -9.99           -0.99
1958-06  1958.4548        317.27   315.15            -1  -9.99           -0.99
1958-07  1958.5370        315.87   315.20            -1  -9.99           -0.99

---
## 4. Explorando DataFrames

### 4.1 Métodos rápidos de exploración

In [ ]:
# Primeras filas
clima_df.head(10)

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto
5,CUSC_002,2024-07-01,15.3,0.0,42,Cusco
6,CUSC_002,2024-07-02,14.8,2.3,55,Cusco
7,CUSC_002,2024-07-03,13.5,8.7,68,Cusco
8,CUSC_002,2024-07-04,16.2,0.0,45,Cusco
9,CUSC_002,2024-07-05,14.9,0.5,51,Cusco

In [ ]:
# Últimas filas
clima_df.tail(3)

  estacion_id       fecha  temperatura_c  precipitacion_mm  humedad_pct region
7    CUSC_002  2024-07-03           13.5               8.7           68  Cusco
8    CUSC_002  2024-07-04           16.2               0.0           45  Cusco
9    CUSC_002  2024-07-05           14.9               0.5           51  Cusco

In [ ]:
# Información del DataFrame
clima_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   estacion_id       10 non-null     object
 1   fecha             10 non-null     object
 2   temperatura_c     10 non-null     float64
 3   precipitacion_mm  10 non-null     float64
 4   humedad_pct       10 non-null     int64
 5   region            10 non-null     object
dtypes: float64(2), int64(1), object(3)
memory usage: 612.0+ bytes

In [ ]:
# Estadísticas descriptivas para columnas numéricas
clima_df.describe()

       temperatura_c  precipitacion_mm  humedad_pct
count      10.000000         10.000000    10.000000
mean       22.980000          6.730000    68.700000
std         8.520668         10.758981    18.903556
min        13.500000          0.000000    42.000000
25%        15.000000          0.000000    52.000000
50%        23.000000          1.400000    74.000000
75%        31.025000          7.800000    84.250000
max        32.100000         32.500000    91.000000

In [ ]:
# Valores únicos en una columna
print(f"Estaciones: {clima_df['estacion_id'].unique()}")
print(f"Número de estaciones: {clima_df['estacion_id'].nunique()}")

Estaciones: ['IQUI_001' 'CUSC_002']
Número de estaciones: 2

In [ ]:
# Conteo de valores
clima_df['region'].value_counts()

region
Loreto    5
Cusco     5
Name: count, dtype: int64

In [ ]:
# Gráficos rápidos con pandas
!pip install sweetviz

Collecting sweetviz
  Downloading sweetviz-2.3.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.2.3)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (2.1.3)
Requirement already satisfied: matplotlib>=3.1.3 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.10.0)
Requirement already satisfied: tqdm>=4.43.0 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (4.67.3)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in /usr/local/lib/python3.13/dist-packages (from sweetviz) (3.1.6)
Collecting importlib_resources>=1.2.0 (from sweetviz)
  Downloading importlib_resources-7.1.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2>=2.11.1->sweetviz) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (26.3)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Downloading sweetviz-2.3.3-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 65.5 MB/s eta 0:00:00
Downloading importlib_resources-7.1.0-py3-none-any.whl (37 kB)
Installing collected packages: importlib_resources, sweetviz
Successfully installed importlib_resources-7.1.0 sweetviz-2.3.3

In [ ]:
import sweetviz as sv
report = sv.analyze(clima_df)
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [ ]:
!pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.1-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.4/400.4 kB 18.8 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 15.8 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 69.3 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 30.8 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 4.6 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.5 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.1

In [ ]:
# Installation via pip
!pip install ydata-profiling
from ydata_profiling import ProfileReport
profile = ProfileReport(clima_df, title="Reporte de dataframe de clima")

# Display in notebook
profile.to_notebook_iframe()

# Export as HTML file
profile.to_file("report.html")

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.2.3)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.13.4)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.1.3)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (4.6.0)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling) (0.61.2)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.3)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.44.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.3)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.13/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.46.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.7.22)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 2.9 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 11.2 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 23.5 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (682 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 40.1 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.2 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.9 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.4

/tmp/ipykernel_3628/2689956692.py:3: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 6/6 [00:00<00:00, 69.76it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

### 🔬 Ejercicio rápido 2 – Exploración

Usando `clima_df`:
1. ¿Cuál es la temperatura máxima y mínima registrada en todo el dataset?
2. ¿Cuántos registros tiene cada estación?
3. ¿Cuál es la precipitación total acumulada en el dataset?

In [ ]:
# Tu código aquí
# temp_max = ???
# temp_min = ???
# conteo_por_estacion = ???
# precip_total = ???

### 4.2 Seleccionando columnas

In [ ]:
# Seleccionar una sola columna (retorna una Series)
temps = clima_df['temperatura_c']
print(type(temps))
temps

<class 'pandas.core.series.Series'>

0    30.5
1    31.2
2    29.8
3    32.1
4    31.5
5    15.3
6    14.8
7    13.5
8    16.2
9    14.9
Name: temperatura_c, dtype: float64

In [ ]:
# Seleccionar múltiples columnas (retorna un DataFrame)
subconjunto = clima_df[['estacion_id', 'fecha', 'temperatura_c']]
subconjunto

  estacion_id       fecha  temperatura_c
0    IQUI_001  2024-07-01           30.5
1    IQUI_001  2024-07-02           31.2
2    IQUI_001  2024-07-03           29.8
3    IQUI_001  2024-07-04           32.1
4    IQUI_001  2024-07-05           31.5
5    CUSC_002  2024-07-01           15.3
6    CUSC_002  2024-07-02           14.8
7    CUSC_002  2024-07-03           13.5
8    CUSC_002  2024-07-04           16.2
9    CUSC_002  2024-07-05           14.9

### 4.3 Seleccionando filas con `.loc` y `.iloc`

In [ ]:
# .iloc – seleccionar por posición entera
print("Primera fila:")
print(clima_df.iloc[0])

print("\nFilas 2-4:")
clima_df.iloc[2:5]

Primera fila:
estacion_id           IQUI_001
fecha               2024-07-01
temperatura_c             30.5
precipitacion_mm          18.2
humedad_pct                 88
region                  Loreto
Name: 0, dtype: object

Filas 2-4:

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto

In [ ]:
# .iloc con selección de filas y columnas
# Obtener filas 0-2, columnas 1-3
clima_df.iloc[0:3, 1:4]

        fecha  temperatura_c  precipitacion_mm
0  2024-07-01           30.5              18.2
1  2024-07-02           31.2               0.0
2  2024-07-03           29.8              32.5

In [ ]:
# .loc – seleccionar por etiqueta
# Primero, establecer un índice significativo
clima_indexado = clima_df.set_index('fecha')
clima_indexado.head()

           estacion_id  temperatura_c  precipitacion_mm  humedad_pct  region
fecha
2024-07-01    IQUI_001           30.5              18.2           88  Loreto
2024-07-02    IQUI_001           31.2               0.0           82  Loreto
2024-07-03    IQUI_001           29.8              32.5           91  Loreto
2024-07-04    IQUI_001           32.1               5.1           85  Loreto
2024-07-05    IQUI_001           31.5               0.0           80  Loreto

In [ ]:
# Seleccionar por índice de fecha
clima_indexado.loc['2024-07-03']

           estacion_id  temperatura_c  precipitacion_mm  humedad_pct  region
fecha
2024-07-03    IQUI_001           29.8              32.5           91  Loreto
2024-07-03    CUSC_002           13.5               8.7           68   Cusco

---
## 5. Filtrado y Manipulación de Datos

### 5.1 Filtrado booleano

In [ ]:
clima_df['temperatura_c'] > 30

0     True
1     True
2    False
3     True
4     True
5    False
6    False
7    False
8    False
9    False
Name: temperatura_c, dtype: bool

In [ ]:
# Filtrar filas donde la temperatura > 30°C (días calurosos en Iquitos)
dias_calurosos = clima_df[clima_df['temperatura_c'] > 30]
dias_calurosos

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto

In [ ]:
# Condiciones múltiples: usar & (y), | (o), ~ (no)
# ¡IMPORTANTE: Cada condición debe estar entre paréntesis!

# Días calurosos Y lluviosos en la selva
caluroso_lluvioso = clima_df[
    (clima_df['temperatura_c'] > 30) &
    (clima_df['precipitacion_mm'] > 0)
]
caluroso_lluvioso

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto

In [ ]:
# Filtrar por estación específica
estacion_iqui = clima_df[clima_df['estacion_id'] == 'IQUI_001']
estacion_iqui

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto

In [ ]:
# Usando el método .query() – a menudo más legible
resultado = clima_df.query('temperatura_c > 30 and precipitacion_mm > 0')
resultado

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto

### 🔬 Ejercicio rápido 3 – Filtrado

El SENAMHI define un **día seco** como aquel con precipitación = 0 mm, y un **día húmedo** con precipitación > 5 mm.

Usando `clima_df`:
1. Filtra solo los días secos
2. Filtra solo los días húmedos
3. ¿En qué región hay más días húmedos?

In [ ]:
# Tu código aquí
# dias_secos  = ???
# dias_humedos = ???

### 5.2 Agregando y modificando columnas

In [ ]:
# Hacer una copia para no modificar el original
df_trabajo = clima_df.copy()

# Agregar una nueva columna – temperatura en Fahrenheit
df_trabajo['temperatura_f'] = df_trabajo['temperatura_c'] * 9/5 + 32
df_trabajo

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region,temperatura_f
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto,86.90
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto,88.16
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto,85.64
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto,89.78
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto,88.70
5,CUSC_002,2024-07-01,15.3,0.0,42,Cusco,59.54
6,CUSC_002,2024-07-02,14.8,2.3,55,Cusco,58.64
7,CUSC_002,2024-07-03,13.5,8.7,68,Cusco,56.30
8,CUSC_002,2024-07-04,16.2,0.0,45,Cusco,61.16
9,CUSC_002,2024-07-05,14.9,0.5,51,Cusco,58.82

In [ ]:
# Agregar columna basada en condición
df_trabajo['es_lluvioso'] = df_trabajo['precipitacion_mm'] > 0
df_trabajo

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region,temperatura_f,es_lluvioso
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto,86.90,True
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto,88.16,False
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto,85.64,True
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto,89.78,True
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto,88.70,False
5,CUSC_002,2024-07-01,15.3,0.0,42,Cusco,59.54,False
6,CUSC_002,2024-07-02,14.8,2.3,55,Cusco,58.64,True
7,CUSC_002,2024-07-03,13.5,8.7,68,Cusco,56.30,True
8,CUSC_002,2024-07-04,16.2,0.0,45,Cusco,61.16,False
9,CUSC_002,2024-07-05,14.9,0.5,51,Cusco,58.82,True

In [ ]:
# Categorizar usando np.where (if-else para arreglos)
import numpy as np
df_trabajo['categoria_temp'] = np.where(df_trabajo['temperatura_c'] >= 25, 'Cálido', 'Fresco')
df_trabajo

,estacion_id,fecha,temperatura_c,precipitacion_mm,humedad_pct,region,temperatura_f,es_lluvioso,categoria_temp
0,IQUI_001,2024-07-01,30.5,18.2,88,Loreto,86.90,True,Cálido
1,IQUI_001,2024-07-02,31.2,0.0,82,Loreto,88.16,False,Cálido
2,IQUI_001,2024-07-03,29.8,32.5,91,Loreto,85.64,True,Cálido
3,IQUI_001,2024-07-04,32.1,5.1,85,Loreto,89.78,True,Cálido
4,IQUI_001,2024-07-05,31.5,0.0,80,Loreto,88.70,False,Cálido
5,CUSC_002,2024-07-01,15.3,0.0,42,Cusco,59.54,False,Fresco
6,CUSC_002,2024-07-02,14.8,2.3,55,Cusco,58.64,True,Fresco
7,CUSC_002,2024-07-03,13.5,8.7,68,Cusco,56.30,True,Fresco
8,CUSC_002,2024-07-04,16.2,0.0,45,Cusco,61.16,False,Fresco
9,CUSC_002,2024-07-05,14.9,0.5,51,Cusco,58.82,True,Fresco

In [ ]:
# Múltiples categorías con pd.cut – clasificación de precipitación
df_trabajo['clase_lluvia'] = pd.cut(
    df_trabajo['precipitacion_mm'],
    bins=[-0.1, 0, 5, 20, 1000],
    labels=['Sin lluvia', 'Llovizna', 'Moderada', 'Intensa']
)
df_trabajo[['estacion_id', 'precipitacion_mm', 'clase_lluvia']]

  estacion_id  precipitacion_mm clase_lluvia
0    IQUI_001              18.2     Moderada
1    IQUI_001               0.0   Sin lluvia
2    IQUI_001              32.5      Intensa
3    IQUI_001               5.1     Moderada
4    IQUI_001               0.0   Sin lluvia
5    CUSC_002               0.0   Sin lluvia
6    CUSC_002               2.3     Llovizna
7    CUSC_002               8.7     Moderada
8    CUSC_002               0.0   Sin lluvia
9    CUSC_002               0.5     Llovizna

### 🔬 Ejercicio rápido 4 – Nuevas columnas

En el inventario forestal `df` de Madre de Dios:
1. Agrega una columna `area_basal_cm2` calculada como π × (DAP/2)²
2. Agrega una columna `clase_diametrica` usando `pd.cut` con los rangos del SERFOR:
   - `'Brinzal'`: DAP < 10 cm
   - `'Latizal'`: 10–25 cm
   - `'Fustal'`: 25–60 cm
   - `'Emergente'`: > 60 cm

In [ ]:
# Tu código aquí
import math

# df['area_basal_cm2'] = ???
# df['clase_diametrica'] = pd.cut(???)

### 5.3 Manejo de datos faltantes

In [ ]:
# Crear datos con valores faltantes – ejemplo de monitoreo en ríos amazónicos
datos_rios = pd.DataFrame({
    'sitio':        ['Ucayali', 'Ucayali', 'Napo', 'Napo', 'Madre de Dios'],
    'temperatura':  [28.5, np.nan, 27.3, 29.1, np.nan],
    'turbidez_ntu': [35.2, 38.8, np.nan, 41.1, 33.5]
})
datos_rios

           sitio  temperatura  turbidez_ntu
0        Ucayali         28.5          35.2
1        Ucayali          NaN          38.8
2           Napo         27.3           NaN
3           Napo         29.1          41.1
4  Madre de Dios          NaN          33.5

In [ ]:
# Verificar valores faltantes
print("Valores faltantes por columna:")
print(datos_rios.isna().sum())

Valores faltantes por columna:
sitio           0
temperatura     2
turbidez_ntu    1
dtype: int64

In [ ]:
# Eliminar filas con cualquier valor faltante
datos_rios.dropna()

     sitio  temperatura  turbidez_ntu
0  Ucayali         28.5          35.2
3     Napo         29.1          41.1

In [ ]:
# Rellenar valores faltantes con la media
datos_rios.fillna(datos_rios.mean(numeric_only=True))

           sitio  temperatura  turbidez_ntu
0        Ucayali         28.5         35.20
1        Ucayali         28.3         38.80
2           Napo         27.3         37.15
3           Napo         29.1         41.10
4  Madre de Dios         28.3         33.50

---
## 6. Agrupamiento y Agregación

Una de las funcionalidades más potentes de pandas es el patrón dividir-aplicar-combinar usando `groupby()`.

In [ ]:
# Agrupar por estación y calcular la media
medias_estacion = clima_df.groupby('estacion_id').mean(numeric_only=True)
medias_estacion

             temperatura_c  precipitacion_mm  humedad_pct
estacion_id
CUSC_002             14.94              2.30         52.2
IQUI_001             31.02             11.16         85.2

In [ ]:
# Múltiples funciones de agregación sobre temperatura
stats_estacion = clima_df.groupby('estacion_id')['temperatura_c'].agg(
    ['mean', 'min', 'max', 'std']
)
stats_estacion

              mean   min   max       std
estacion_id
CUSC_002     14.94  13.5  16.2  0.976217
IQUI_001     31.02  29.8  32.1  0.892749

In [ ]:
# Diferentes agregaciones para diferentes columnas
resumen = clima_df.groupby('region').agg({
    'temperatura_c'   : ['mean', 'std'],
    'precipitacion_mm': 'sum',
    'humedad_pct'     : 'mean'
})
resumen

       temperatura_c           precipitacion_mm humedad_pct
                mean       std              sum        mean
region
Cusco          14.94  0.976217             11.5        52.2
Loreto         31.02  0.892749             55.8        85.2

In [ ]:
# Contar observaciones por grupo
clima_df.groupby('region').size()

region
Cusco     5
Loreto    5
dtype: int64

### 🔬 Ejercicio rápido 5 – Groupby

Usando el inventario forestal `df`:
1. Calcula el DAP medio y el número de árboles **por parcela**
2. ¿Qué especie tiene el DAP medio más alto?
3. Calcula el área basal total por especie (necesitas el ejercicio 4 resuelto)

In [ ]:
df

   arbol_id                  especie  dap_cm  altura_m  parcela
0         1    Swietenia macrophylla    52.7      34.5  MDD_023
1         2          Cedrela odorata    38.4      28.1  MDD_023
2         3  Cedrelinga cateniformis    61.2      40.3  MDD_024
3         4      Virola surinamensis    29.5      22.6  MDD_024
4         5    Swietenia macrophylla    44.8      31.8  MDD_025

In [ ]:
# Tu código aquí
# stats_parcela = df.groupby(???).agg(???)
# especie_mayor_dap = df.groupby(???)[???].mean().idxmax()

---
## 7. Miniproyecto: Análisis de Inventario Forestal – Madre de Dios

Combinamos todo lo aprendido en un flujo de análisis completo, similar al que usa el **SERFOR** para procesar inventarios forestales.

In [ ]:
# Crear un inventario forestal más completo
import pandas as pd
import numpy as np

inventario = pd.DataFrame({
    'arbol_id': range(1, 21),
    'especie': [
        'Swietenia macrophylla', 'Cedrela odorata', 'Swietenia macrophylla',
        'Cedrelinga cateniformis', 'Virola surinamensis', 'Cedrela odorata',
        'Swietenia macrophylla', 'Cedrelinga cateniformis', 'Cedrela odorata',
        'Virola surinamensis', 'Swietenia macrophylla', 'Cedrela odorata',
        'Cedrelinga cateniformis', 'Virola surinamensis', 'Swietenia macrophylla',
        'Cedrela odorata', 'Cedrelinga cateniformis', 'Virola surinamensis',
        'Swietenia macrophylla', 'Cedrela odorata'
    ],
    'dap_cm': [52.7, 38.4, 61.2, 29.5, 44.8, 35.1, 48.3, 72.1, 41.5, 28.9,
               55.0, 33.8, 65.4, 38.2, 50.6, 42.0, 58.7, 31.4, 47.9, 36.5],
    'altura_m': [34.5, 28.1, 40.3, 22.6, 31.8, 26.4, 32.7, 45.2, 29.3, 21.8,
                 36.0, 25.9, 42.1, 28.5, 33.4, 30.2, 38.9, 23.7, 31.5, 27.3],
    'parcela': ['MDD_023']*7 + ['MDD_024']*7 + ['MDD_025']*6,
    'estado': ['sano']*16 + ['danado', 'sano', 'danado', 'sano']
})

print(f"Inventario cargado: {len(inventario)} árboles")
inventario.head()

Inventario cargado: 20 árboles

   arbol_id                  especie  dap_cm  altura_m  parcela estado
0         1    Swietenia macrophylla    52.7      34.5  MDD_023   sano
1         2          Cedrela odorata    38.4      28.1  MDD_023   sano
2         3    Swietenia macrophylla    61.2      40.3  MDD_023   sano
3         4  Cedrelinga cateniformis    29.5      22.6  MDD_023   sano
4         5      Virola surinamensis    44.8      31.8  MDD_023   sano

In [ ]:
# ── Paso 1: Exploración inicial ──
print("=== Resumen del inventario ===")
print(f"Total de árboles: {len(inventario)}")
print(f"Parcelas: {inventario['parcela'].unique()}")
print(f"Especies: {inventario['especie'].nunique()} especies únicas")
print()
print(inventario.describe())

=== Resumen del inventario ===
Total de árboles: 20
Parcelas: ['MDD_023' 'MDD_024' 'MDD_025']
Especies: 4 especies únicas

       arbol_id     dap_cm   altura_m
count  20.00000  20.000000  20.000000
mean   10.50000  45.600000  31.510000
std     5.91608  12.343036   6.500518
min     1.00000  28.900000  21.800000
25%     5.75000  36.150000  27.075000
50%    10.50000  43.400000  30.850000
75%    15.25000  53.275000  34.875000
max    20.00000  72.100000  45.200000

In [ ]:
# ── Paso 2: Calcular campos derivados ──
inventario['area_basal_cm2'] = np.pi * (inventario['dap_cm'] / 2) ** 2

inventario['clase_diam'] = pd.cut(
    inventario['dap_cm'],
    bins=[0, 25, 40, 60, 1000],
    labels=['Latizal', 'Fustal bajo', 'Fustal alto', 'Emergente']
)

inventario['apto_aprovechamiento'] = inventario['dap_cm'] >= 40

inventario[['especie', 'dap_cm', 'area_basal_cm2', 'clase_diam', 'apto_aprovechamiento']].head(8)

,especie,dap_cm,area_basal_cm2,clase_diam,apto_aprovechamiento
0,Swietenia macrophylla,52.7,2181.278465,Fustal alto,True
1,Cedrela odorata,38.4,1158.116716,Fustal bajo,False
2,Swietenia macrophylla,61.2,2941.661697,Emergente,True
3,Cedrelinga cateniformis,29.5,683.492752,Fustal bajo,False
4,Virola surinamensis,44.8,1576.325530,Fustal alto,True
5,Cedrela odorata,35.1,967.618391,Fustal bajo,False
6,Swietenia macrophylla,48.3,1832.247521,Fustal alto,True
7,Cedrelinga cateniformis,72.1,4082.821667,Emergente,True

In [ ]:
# ── Paso 3: Filtrado – árboles aptos para aprovechamiento ──
aptos = inventario[inventario['apto_aprovechamiento'] & (inventario['estado'] == 'sano')]
print(f"Árboles aptos para aprovechamiento: {len(aptos)} de {len(inventario)}")
aptos[['arbol_id', 'especie', 'dap_cm', 'parcela']].head()

Árboles aptos para aprovechamiento: 10 de 20

   arbol_id                  especie  dap_cm  parcela
0         1    Swietenia macrophylla    52.7  MDD_023
2         3    Swietenia macrophylla    61.2  MDD_023
4         5      Virola surinamensis    44.8  MDD_023
6         7    Swietenia macrophylla    48.3  MDD_023
7         8  Cedrelinga cateniformis    72.1  MDD_024

In [ ]:
# ── Paso 4: Resumen por especie ──
resumen_especie = inventario.groupby('especie').agg(
    n_arboles    = ('arbol_id', 'count'),
    dap_medio    = ('dap_cm', 'mean'),
    dap_max      = ('dap_cm', 'max'),
    altura_media = ('altura_m', 'mean'),
    ab_total_cm2 = ('area_basal_cm2', 'sum')
).round(2)

resumen_especie

,n_arboles,dap_medio,dap_max,altura_media,ab_total_cm2
especie,,,,,
Cedrela odorata,6,37.88,42.0,27.87,6807.45
Cedrelinga cateniformis,4,56.42,72.1,37.20,10831.83
Swietenia macrophylla,6,52.62,61.2,34.73,13143.94
Virola surinamensis,4,35.83,44.8,26.45,4152.75

In [ ]:
# ── Paso 5: Resumen por parcela ──
resumen_parcela = inventario.groupby('parcela').agg(
    n_arboles    = ('arbol_id', 'count'),
    dap_medio    = ('dap_cm', 'mean'),
    ab_total_cm2 = ('area_basal_cm2', 'sum'),
    n_especies   = ('especie', 'nunique')
).round(2)

print("=== Resumen por parcela ===")
print(resumen_parcela)

=== Resumen por parcela ===
         n_arboles  dap_medio  ab_total_cm2  n_especies
parcela
MDD_023          7      44.29      11340.74           4
MDD_024          7      47.84      13869.90           4
MDD_025          6      44.52       9725.33           4

In [ ]:
# ── Paso 6: Exportar resultados ──
inventario.to_csv('inventario_procesado_mdd.csv', index=False)
resumen_especie.to_csv('resumen_por_especie_mdd.csv')

print("✅ Archivos exportados:")
print("   - inventario_procesado_mdd.csv")
print("   - resumen_por_especie_mdd.csv")

✅ Archivos exportados:
   - inventario_procesado_mdd.csv
   - resumen_por_especie_mdd.csv

In [ ]:
# Verificar el archivo exportado
pd.read_csv('inventario_procesado_mdd.csv').head()

,arbol_id,especie,dap_cm,altura_m,parcela,estado,area_basal_cm2,clase_diam,apto_aprovechamiento
0,1,Swietenia macrophylla,52.7,34.5,MDD_023,sano,2181.278465,Fustal alto,True
1,2,Cedrela odorata,38.4,28.1,MDD_023,sano,1158.116716,Fustal bajo,False
2,3,Swietenia macrophylla,61.2,40.3,MDD_023,sano,2941.661697,Emergente,True
3,4,Cedrelinga cateniformis,29.5,22.6,MDD_023,sano,683.492752,Fustal bajo,False
4,5,Virola surinamensis,44.8,31.8,MDD_023,sano,1576.325530,Fustal alto,True

---
## 8. Ejercicios adicionales

Ejercicios integradores con datos reales del Perú.

### Ejercicio 1: Análisis de CO2 atmosférico

Usando el dataset de CO2 de Mauna Loa cargado anteriormente (`co2_df`):

1. Agrupa por año y calcula la concentración media anual de CO2 (`Average`)
2. Encuentra el año con la concentración más alta
3. Calcula el incremento medio anual de CO2 entre 2000 y 2024
4. ¿En qué año la concentración media superó por primera vez las 400 ppm?

**Pista:** La columna de año se llama `'Year'` y el CO2 `'Average'`

In [ ]:
# Tu código aquí – Ejercicio 1: CO2

# co2_anual = co2_df.groupby(???)[???].mean()
# anio_max = ???
# incremento_anual = ???
# primer_anio_400 = ???

### Ejercicio 2: Monitoreo de calidad de agua

El INAIGEM registra parámetros fisicoquímicos en 5 puntos de la cuenca del Mantaro. Crea un DataFrame con los siguientes datos y analízalos:

| Sitio | pH | OD (mg/L) | Turbidez (NTU) | Temp (°C) |
|-------|----|-----------|----------------|-----------|
| Junín | 7.2 | 6.8 | 18.5 | 9.5 |
| Huancayo | 6.1 | 3.2 | 85.4 | 13.2 |
| Pampas | 7.0 | 7.5 | 12.3 | 11.8 |
| Mayocc | 6.8 | 5.9 | 22.1 | 14.5 |
| Tambo | 7.1 | 6.2 | 31.8 | 16.3 |

1. Determina si cumple los **Estándares de Calidad Ambiental (ECA)** del MINAM para pH (6.5–8.5) y OD (≥ 5 mg/L)
2. Clasifica la turbidez en `'Baja'` (< 25 NTU), `'Media'` (25–50), `'Alta'` (> 50)
3. Calcula un **índice de alerta** que sea `True` si falla al menos 1 parámetro ECA

In [ ]:
# Tu código aquí – Ejercicio 3: Calidad de agua
calidad_agua = pd.DataFrame({
    'sitio'     : ['Junín', 'Huancayo', 'Pampas', 'Mayocc', 'Tambo'],
    'ph'        : [7.2, 6.1, 7.0, 6.8, 7.1],
    'od_mgl'    : [6.8, 3.2, 7.5, 5.9, 6.2],
    'turbidez'  : [18.5, 85.4, 12.3, 22.1, 31.8],
    'temp_c'    : [9.5, 13.2, 11.8, 14.5, 16.3]
})

# cumple_ph  = ???
# cumple_od  = ???
# clase_turb = pd.cut(???)
# alerta     = ???

---
## Resumen

**Conceptos clave de hoy:**

1. **Paquetes**: importar con `import`, usar alias como `np`, `pd`
2. **Arreglos NumPy**: operaciones numéricas rápidas, indexación booleana
3. **DataFrames de pandas**: datos tabulares con filas y columnas etiquetadas
4. **Carga de datos**: `pd.read_csv()`, puede cargar desde URLs
5. **Selección**: `[]` para columnas, `.loc`/`.iloc` para filas
6. **Filtrado**: condiciones booleanas, método `.query()`
7. **Agregación**: `groupby()` + funciones de agregación

**Aplicaciones en el contexto peruano:**
- Procesamiento de datos del **SENAMHI** (temperatura, precipitación)
- Inventarios forestales del **SERFOR** en Madre de Dios y Ucayali
- Monitoreo de calidad del agua del **INAIGEM** en cuencas andinas
- Análisis de CO2 atmosférico para estudios climáticos

**Próxima clase:** Análisis estadístico con SciPy y visualización con Matplotlib

---
## Soluciones a los ejercicios

In [ ]:
# Solución Ejercicio rápido 1 – NumPy
ndvi = np.array([0.72, 0.85, 0.61, 0.78, 0.90, 0.55, 0.83, 0.69])

print(f"Media NDVI:    {np.mean(ndvi):.3f}")
print(f"Mínimo NDVI:   {np.min(ndvi):.3f}")
print(f"Máximo NDVI:   {np.max(ndvi):.3f}")
print(f"Píxeles bosque (NDVI > 0.75): {np.sum(ndvi > 0.75)}")
print(f"Desv. Estándar: {np.std(ndvi):.3f}")

In [ ]:
# Solución Ejercicio rápido 2 – Exploración
print(f"Temperatura máxima: {clima_df['temperatura_c'].max()} °C")
print(f"Temperatura mínima: {clima_df['temperatura_c'].min()} °C")
print()
print("Registros por estación:")
print(clima_df['estacion_id'].value_counts())
print()
print(f"Precipitación total acumulada: {clima_df['precipitacion_mm'].sum():.1f} mm")

In [ ]:
# Solución Ejercicio rápido 3 – Filtrado
dias_secos   = clima_df[clima_df['precipitacion_mm'] == 0]
dias_humedos = clima_df[clima_df['precipitacion_mm'] > 5]

print(f"Días secos:   {len(dias_secos)}")
print(f"Días húmedos: {len(dias_humedos)}")
print()
print("Días húmedos por región:")
print(dias_humedos['region'].value_counts())

In [ ]:
# Solución Ejercicio rápido 4 – Nuevas columnas
df_sol = df.copy()
df_sol['area_basal_cm2'] = np.pi * (df_sol['dap_cm'] / 2) ** 2
df_sol['clase_diametrica'] = pd.cut(
    df_sol['dap_cm'],
    bins=[0, 10, 25, 60, 1000],
    labels=['Brinzal', 'Latizal', 'Fustal', 'Emergente']
)
df_sol[['especie', 'dap_cm', 'area_basal_cm2', 'clase_diametrica']]

In [ ]:
# Solución Ejercicio rápido 5 – Groupby
stats_parcela = df_sol.groupby('parcela').agg(
    n_arboles   = ('arbol_id', 'count'),
    dap_medio   = ('dap_cm', 'mean')
).round(2)
print("Stats por parcela:")
print(stats_parcela)
print()
especie_mayor_dap = df_sol.groupby('especie')['dap_cm'].mean().idxmax()
print(f"Especie con mayor DAP medio: {especie_mayor_dap}")

In [ ]:
# Solución Ejercicio 1 – CO2 Mauna Loa
co2_anual = co2_df.groupby('Year')['Average'].mean()

print("CO2 medio anual (últimos 5 años):")
print(co2_anual.tail())
print()

anio_max = co2_anual.idxmax()
co2_max  = co2_anual.max()
print(f"Año con mayor CO2: {anio_max} ({co2_max:.2f} ppm)")
print()

co2_2000_2024 = co2_anual.loc[2000:2024]
incremento = (co2_2000_2024.iloc[-1] - co2_2000_2024.iloc[0]) / len(co2_2000_2024)
print(f"Incremento medio anual (2000–2024): {incremento:.2f} ppm/año")
print()

primer_400 = co2_anual[co2_anual >= 400].index[0]
print(f"Primer año con CO2 medio >= 400 ppm: {primer_400}")

In [ ]:
# Solución Ejercicio 2 – Calidad de agua (ECA-MINAM)
calidad_agua = pd.DataFrame({
    'sitio'     : ['Junín', 'Huancayo', 'Pampas', 'Mayocc', 'Tambo'],
    'ph'        : [7.2, 6.1, 7.0, 6.8, 7.1],
    'od_mgl'    : [6.8, 3.2, 7.5, 5.9, 6.2],
    'turbidez'  : [18.5, 85.4, 12.3, 22.1, 31.8],
    'temp_c'    : [9.5, 13.2, 11.8, 14.5, 16.3]
})

calidad_agua['cumple_ph']   = (calidad_agua['ph'] >= 6.5) & (calidad_agua['ph'] <= 8.5)
calidad_agua['cumple_od']   = calidad_agua['od_mgl'] >= 5
calidad_agua['clase_turb']  = pd.cut(
    calidad_agua['turbidez'],
    bins=[-0.1, 25, 50, 1000],
    labels=['Baja', 'Media', 'Alta']
)
calidad_agua['alerta_eca'] = ~(calidad_agua['cumple_ph'] & calidad_agua['cumple_od'])

print("Evaluación ECA-MINAM – Cuenca del Mantaro:")
print(calidad_agua[['sitio', 'cumple_ph', 'cumple_od', 'clase_turb', 'alerta_eca']])